{
  "formatVersion": "1.1",
  "component": {
    "group": "io.carrotquest",
    "module": "image-picker",
    "version": "1.0.11-usRelease",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "luidwsiegvfx7bccdoswuimehe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.14"
          }
        },
        {
          "group": "com.github.tbruyelle",
          "module": "rxpermissions",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.1.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "image-picker-1.0.11-usRelease.aar",
          "url": "image-picker-1.0.11-usRelease.aar",
          "size": 347539,
          "sha512": "ba7d5a662cf10905344f4b0b55947ce5ab566f622db90c678edeb80d05faceba1684f0de424bc75de6466288fdb7254f9c53640369dc8bded0523f1eadccaa51",
          "sha256": "2bad216fb7ae579b3904385ca3d5393b159363f212caa07aae6570268786f0c5",
          "sha1": "6edcb88f6a6b811f587d66709ae89208d4059da5",
          "md5": "98fe00405944b8c994560446e3481e0d"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "image-picker-1.0.11-usRelease.aar",
          "url": "image-picker-1.0.11-usRelease.aar",
          "size": 347539,
          "sha512": "ba7d5a662cf10905344f4b0b55947ce5ab566f622db90c678edeb80d05faceba1684f0de424bc75de6466288fdb7254f9c53640369dc8bded0523f1eadccaa51",
          "sha256": "2bad216fb7ae579b3904385ca3d5393b159363f212caa07aae6570268786f0c5",
          "sha1": "6edcb88f6a6b811f587d66709ae89208d4059da5",
          "md5": "98fe00405944b8c994560446e3481e0d"
        }
      ]
    }
  ]
}
