{
  "formatVersion": "1.1",
  "component": {
    "group": "io.carrotquest",
    "module": "image-picker",
    "version": "1.0.12-commonRelease",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "slh7otyimff5jhz77qwof74b4y"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.14"
          }
        },
        {
          "group": "com.github.tbruyelle",
          "module": "rxpermissions",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.1.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "image-picker-1.0.12-commonRelease.aar",
          "url": "image-picker-1.0.12-commonRelease.aar",
          "size": 280017,
          "sha512": "d83a408491f95a4ce0fcbef7ea9afdad9ed5c2012e3d905258b10c9d808ed8c4149696d46c7a9ad54134114591cffbed34e22884c477f18076b3290361b76237",
          "sha256": "5516f6fc0e57a186e7ac99414540152e1a301c6e1ba4c96e900448e02cd2fe09",
          "sha1": "7a0fab9163f05bf65401b0dcad5fbbfe019eb472",
          "md5": "b35dbf06164d1fbce96ad5189a1a2752"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "image-picker-1.0.12-commonRelease.aar",
          "url": "image-picker-1.0.12-commonRelease.aar",
          "size": 280017,
          "sha512": "d83a408491f95a4ce0fcbef7ea9afdad9ed5c2012e3d905258b10c9d808ed8c4149696d46c7a9ad54134114591cffbed34e22884c477f18076b3290361b76237",
          "sha256": "5516f6fc0e57a186e7ac99414540152e1a301c6e1ba4c96e900448e02cd2fe09",
          "sha1": "7a0fab9163f05bf65401b0dcad5fbbfe019eb472",
          "md5": "b35dbf06164d1fbce96ad5189a1a2752"
        }
      ]
    }
  ]
}
