{
  "formatVersion": "1.1",
  "component": {
    "group": "io.carrotquest",
    "module": "image-picker",
    "version": "1.0.14-usRelease",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6npoilrhyncbdo3enscpt2fhim"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.14"
          }
        },
        {
          "group": "com.github.tbruyelle",
          "module": "rxpermissions",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image-picker-1.0.14-usRelease.aar",
          "url": "image-picker-1.0.14-usRelease.aar",
          "size": 279163,
          "sha512": "749a7460f846c6cba6f57807850a50c80ca8818c7ef290cde60aa3b072a42ab2860795c626b7e19ce0c13b5b0d79bb7f23116fb1d9677a7c8c7aa75ee76dc4a5",
          "sha256": "a4c39f22498c42158b2b5a95c44ecbfc4a971d01ac69526184295fada0d1f381",
          "sha1": "d2737c0d9a09dc9cd1e670a33a8c58e6a644e7f1",
          "md5": "62eb75a7a3cf27037e35ec1a97357e2a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "image-picker-1.0.14-usRelease.aar",
          "url": "image-picker-1.0.14-usRelease.aar",
          "size": 279163,
          "sha512": "749a7460f846c6cba6f57807850a50c80ca8818c7ef290cde60aa3b072a42ab2860795c626b7e19ce0c13b5b0d79bb7f23116fb1d9677a7c8c7aa75ee76dc4a5",
          "sha256": "a4c39f22498c42158b2b5a95c44ecbfc4a971d01ac69526184295fada0d1f381",
          "sha1": "d2737c0d9a09dc9cd1e670a33a8c58e6a644e7f1",
          "md5": "62eb75a7a3cf27037e35ec1a97357e2a"
        }
      ]
    }
  ]
}
