{
  "formatVersion": "1.1",
  "component": {
    "group": "io.carrotquest",
    "module": "android-sdk",
    "version": "1.0.94-commonRelease",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "commonReleaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:main": "common",
        "main": "common",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.2"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.55"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.55"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.55"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-core",
          "version": {
            "requires": "20.0.2"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "23.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.13"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.android.flexbox",
          "module": "flexbox",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.vdurmont",
          "module": "emoji-java",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.github.Redman1037",
          "module": "TSnackBar",
          "version": {
            "requires": "V2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.michaelrocks",
          "module": "libphonenumber-android",
          "version": {
            "requires": "8.13.35"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "3.12.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.vanniktech",
          "module": "rxpermission",
          "version": {
            "requires": "0.10.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "android-sdk-1.0.94-commonRelease.aar",
          "url": "android-sdk-1.0.94-commonRelease.aar",
          "size": 1233727,
          "sha512": "bdb4d20c257a4292372e4028af2ef5799e4bb175a2ea489ec982526ded104ea619a46f5e6d50e26d05ac7c6c77152b4f0a6bcd6355f3d67614359a93c43d67ef",
          "sha256": "51ccfbe21693ddb409d1f3d24d16cc772cb4ee9eeb1c7e5d173cfac9900fbade",
          "sha1": "61c4ae070ea49fa9283ce6a8d6880fcd989ce28e",
          "md5": "b084582d5226cd04c2f9a64de58ec080"
        }
      ]
    },
    {
      "name": "commonReleaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:main": "common",
        "main": "common",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.2"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.55"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.55"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.55"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-core",
          "version": {
            "requires": "20.0.2"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "23.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.13"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.android.flexbox",
          "module": "flexbox",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.vdurmont",
          "module": "emoji-java",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.github.Redman1037",
          "module": "TSnackBar",
          "version": {
            "requires": "V2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.michaelrocks",
          "module": "libphonenumber-android",
          "version": {
            "requires": "8.13.35"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "3.12.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.vanniktech",
          "module": "rxpermission",
          "version": {
            "requires": "0.10.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "android-sdk-1.0.94-commonRelease.aar",
          "url": "android-sdk-1.0.94-commonRelease.aar",
          "size": 1233727,
          "sha512": "bdb4d20c257a4292372e4028af2ef5799e4bb175a2ea489ec982526ded104ea619a46f5e6d50e26d05ac7c6c77152b4f0a6bcd6355f3d67614359a93c43d67ef",
          "sha256": "51ccfbe21693ddb409d1f3d24d16cc772cb4ee9eeb1c7e5d173cfac9900fbade",
          "sha1": "61c4ae070ea49fa9283ce6a8d6880fcd989ce28e",
          "md5": "b084582d5226cd04c2f9a64de58ec080"
        }
      ]
    },
    {
      "name": "commonReleaseSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:main": "common",
        "main": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "android-sdk-1.0.94-commonRelease-sources.jar",
          "url": "android-sdk-1.0.94-commonRelease-sources.jar",
          "size": 738923,
          "sha512": "880385d38ec75b2c7503491dff93737825fd38ffc67766984e848e4135ec45aee75c63317b373b9e5418000070d8dde02e6e19d1b8c770ce3aa0183049130b8a",
          "sha256": "4b9ac1b406e157febaf16c09219917bf3868deb1649e0d73779ee007b6c9fb6a",
          "sha1": "49f8b1e2efd51fec1dd41fbfb996a6e9600bc2ae",
          "md5": "39ac4401fcb96540092f87c276a14239"
        }
      ]
    }
  ]
}
