{
  "formatVersion": "1.1",
  "component": {
    "group": "io.carrotquest",
    "module": "android-sdk",
    "version": "1.0.78-usRelease",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6jaqggqzprhhpbx7yms3xkjo2m"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.github.Redman1037",
          "module": "TSnackBar",
          "version": {
            "requires": "V2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.2"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.35.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.35.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-core",
          "version": {
            "requires": "20.0.2"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "23.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.14"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.github.tbruyelle",
          "module": "rxpermissions",
          "version": {
            "requires": "0.12"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.13"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.android.flexbox",
          "module": "flexbox",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.vdurmont",
          "module": "emoji-java",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.carrotquest",
          "module": "cqandroid-lib",
          "version": {
            "requires": "1.0.50.1-usRelease"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "android-sdk-1.0.78-usRelease.aar",
          "url": "android-sdk-1.0.78-usRelease.aar",
          "size": 790890,
          "sha512": "1036ec4882e592c8b0fd5dc3436b381f1a0975410428ed0fee887afab42da1fd9c713e105b81b750f5629edd3c430179b686acfe9d78f98a9a23c5fdf950be45",
          "sha256": "9bb33d88d7785d39c3d59baa5e9192953654b8cd54c84ef6165a39acfaa11cf5",
          "sha1": "96150bc083acdea127a22e06801386143dcbff5f",
          "md5": "689c74815fed1575aa2053a658310892"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.github.Redman1037",
          "module": "TSnackBar",
          "version": {
            "requires": "V2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "android-sdk-1.0.78-usRelease.aar",
          "url": "android-sdk-1.0.78-usRelease.aar",
          "size": 790890,
          "sha512": "1036ec4882e592c8b0fd5dc3436b381f1a0975410428ed0fee887afab42da1fd9c713e105b81b750f5629edd3c430179b686acfe9d78f98a9a23c5fdf950be45",
          "sha256": "9bb33d88d7785d39c3d59baa5e9192953654b8cd54c84ef6165a39acfaa11cf5",
          "sha1": "96150bc083acdea127a22e06801386143dcbff5f",
          "md5": "689c74815fed1575aa2053a658310892"
        }
      ]
    }
  ]
}
