{
  "formatVersion": "1.1",
  "component": {
    "group": "io.carrotquest",
    "module": "image-picker",
    "version": "1.0.14-commonRelease",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6npoilrhyncbdo3enscpt2fhim"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.14"
          }
        },
        {
          "group": "com.github.tbruyelle",
          "module": "rxpermissions",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image-picker-1.0.14-commonRelease.aar",
          "url": "image-picker-1.0.14-commonRelease.aar",
          "size": 279281,
          "sha512": "25ff41dd1913cf6aaaa91df2dbe2a6cd37eeb8696b5003f27dcd1218d8fe964921b8fbf10dfc705a5436772b1ce9aea77fcafd6b7635347770f149b171f9bac3",
          "sha256": "374b923c994550f6e8a66cc4be35281b3456b59a10c5b44cf62c476612767f30",
          "sha1": "3326c7d4da5955cd701116d26830dde52f3bb57e",
          "md5": "18dc58a0aef0da24f7d427146f8134f2"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "image-picker-1.0.14-commonRelease.aar",
          "url": "image-picker-1.0.14-commonRelease.aar",
          "size": 279281,
          "sha512": "25ff41dd1913cf6aaaa91df2dbe2a6cd37eeb8696b5003f27dcd1218d8fe964921b8fbf10dfc705a5436772b1ce9aea77fcafd6b7635347770f149b171f9bac3",
          "sha256": "374b923c994550f6e8a66cc4be35281b3456b59a10c5b44cf62c476612767f30",
          "sha1": "3326c7d4da5955cd701116d26830dde52f3bb57e",
          "md5": "18dc58a0aef0da24f7d427146f8134f2"
        }
      ]
    }
  ]
}
