{
  "formatVersion": "1.1",
  "component": {
    "group": "io.carrotquest",
    "module": "cqandroid-lib",
    "version": "1.0.45-commonRelease",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "dizs3n7ol5ft3ajpbfs77fqkpm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.vanniktech",
          "module": "rxpermission",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.35.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.35.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.14"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "cqandroid-lib-1.0.45-commonRelease.aar",
          "url": "cqandroid-lib-1.0.45-commonRelease.aar",
          "size": 281989,
          "sha512": "fdffadda2da682ed72a7730c693107bb7ceb140d3230979f852317e24741c3e733207923033f6c7d7ac1d02d93e66d662822a23363e9731ea7cac893b342d0d2",
          "sha256": "07fbe6e3f0dec76f1d6929869a3060445b5ec1bded6ab34cfe76be5bbbaaaf6b",
          "sha1": "1de2b1d6c0dc3871c18b9d0d449e77333534670a",
          "md5": "f07ac3d2a219e4cfc513620cc6d7ed66"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.vanniktech",
          "module": "rxpermission",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "cqandroid-lib-1.0.45-commonRelease.aar",
          "url": "cqandroid-lib-1.0.45-commonRelease.aar",
          "size": 281989,
          "sha512": "fdffadda2da682ed72a7730c693107bb7ceb140d3230979f852317e24741c3e733207923033f6c7d7ac1d02d93e66d662822a23363e9731ea7cac893b342d0d2",
          "sha256": "07fbe6e3f0dec76f1d6929869a3060445b5ec1bded6ab34cfe76be5bbbaaaf6b",
          "sha1": "1de2b1d6c0dc3871c18b9d0d449e77333534670a",
          "md5": "f07ac3d2a219e4cfc513620cc6d7ed66"
        }
      ]
    }
  ]
}
