{
  "formatVersion": "1.1",
  "component": {
    "group": "io.carrotquest",
    "module": "image-picker",
    "version": "1.0.11-commonRelease",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "luidwsiegvfx7bccdoswuimehe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.14"
          }
        },
        {
          "group": "com.github.tbruyelle",
          "module": "rxpermissions",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.1.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "image-picker-1.0.11-commonRelease.aar",
          "url": "image-picker-1.0.11-commonRelease.aar",
          "size": 347666,
          "sha512": "f262ca2313c7be56e17c565ee5d4076446784516432c635c9a52e9f598c17f738e8d3c080fba8001ef41e9a424d1e078af5293e7fdac5f22b1ad8f0a875a7db8",
          "sha256": "3f980e08b4d961339fd63ed635eea791dfe95f04529f637e82c5a8a7b6c29e04",
          "sha1": "1e984caf4f9b452af865d84cd95c5110680c1755",
          "md5": "d23b7f4d9ff9476e560d02ae56088c25"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "image-picker-1.0.11-commonRelease.aar",
          "url": "image-picker-1.0.11-commonRelease.aar",
          "size": 347666,
          "sha512": "f262ca2313c7be56e17c565ee5d4076446784516432c635c9a52e9f598c17f738e8d3c080fba8001ef41e9a424d1e078af5293e7fdac5f22b1ad8f0a875a7db8",
          "sha256": "3f980e08b4d961339fd63ed635eea791dfe95f04529f637e82c5a8a7b6c29e04",
          "sha1": "1e984caf4f9b452af865d84cd95c5110680c1755",
          "md5": "d23b7f4d9ff9476e560d02ae56088c25"
        }
      ]
    }
  ]
}
