{
  "formatVersion": "1.1",
  "component": {
    "group": "io.carrotquest",
    "module": "cqandroid-lib",
    "version": "1.0.51-commonRelease",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vte572rv6basrk7zezuwlrm7ca"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.vanniktech",
          "module": "rxpermission",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.35.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.35.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.14"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "cqandroid-lib-1.0.51-commonRelease.aar",
          "url": "cqandroid-lib-1.0.51-commonRelease.aar",
          "size": 284517,
          "sha512": "1393a5e828c3ea0f7c17691f0b1f8aea55a759bf833b1138a1649351cab9a869d8d02855fc896062f06ad4c9f1ce6300410875bcd25bda7f592dc18dde6ed079",
          "sha256": "2535c780ca5a28d214a1f268eea3c9e92c10a495720d94a86dca80f56c6b938e",
          "sha1": "1e5164163ff4fa85f53f8fdd1fc8384e5fc7f353",
          "md5": "a7c2514eb7bf82dbc2025a8c982c317a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.vanniktech",
          "module": "rxpermission",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "cqandroid-lib-1.0.51-commonRelease.aar",
          "url": "cqandroid-lib-1.0.51-commonRelease.aar",
          "size": 284517,
          "sha512": "1393a5e828c3ea0f7c17691f0b1f8aea55a759bf833b1138a1649351cab9a869d8d02855fc896062f06ad4c9f1ce6300410875bcd25bda7f592dc18dde6ed079",
          "sha256": "2535c780ca5a28d214a1f268eea3c9e92c10a495720d94a86dca80f56c6b938e",
          "sha1": "1e5164163ff4fa85f53f8fdd1fc8384e5fc7f353",
          "md5": "a7c2514eb7bf82dbc2025a8c982c317a"
        }
      ]
    }
  ]
}
