{
  "formatVersion": "1.1",
  "component": {
    "group": "io.carrotquest",
    "module": "android-sdk",
    "version": "1.0.64-usRelease",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ese2nuwlpbfrfpzojaflzht3im"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.github.Redman1037",
          "module": "TSnackBar",
          "version": {
            "requires": "V2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.carrotquest",
          "module": "image-picker",
          "version": {
            "requires": "1.0.18-usRelease"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.2"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.35.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.35.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-core",
          "version": {
            "requires": "20.0.2"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "23.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.14"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.github.tbruyelle",
          "module": "rxpermissions",
          "version": {
            "requires": "0.12"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.13"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.android.flexbox",
          "module": "flexbox",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.vdurmont",
          "module": "emoji-java",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.carrotquest",
          "module": "cqandroid-lib",
          "version": {
            "requires": "1.0.40-usRelease"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "android-sdk-1.0.64-usRelease.aar",
          "url": "android-sdk-1.0.64-usRelease.aar",
          "size": 1040591,
          "sha512": "d1e8de17a76b30e818a53a9f295c6206eefd0a909122559ac702142e8ef63c8b9c082d1cba5588f523915daf1ce908948dddced10231096ef4a7849e90f8223a",
          "sha256": "e846c3b2ebcaecab63e03b3f8592bdf34bc5d58c009d6273a61aa0b52627496d",
          "sha1": "40d46e53ec5e58e7d323f42968765ef3cdfad5bf",
          "md5": "c28e49525e9cc22fac40cca5b02d1740"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.github.Redman1037",
          "module": "TSnackBar",
          "version": {
            "requires": "V2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.carrotquest",
          "module": "image-picker",
          "version": {
            "requires": "1.0.18-usRelease"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "android-sdk-1.0.64-usRelease.aar",
          "url": "android-sdk-1.0.64-usRelease.aar",
          "size": 1040591,
          "sha512": "d1e8de17a76b30e818a53a9f295c6206eefd0a909122559ac702142e8ef63c8b9c082d1cba5588f523915daf1ce908948dddced10231096ef4a7849e90f8223a",
          "sha256": "e846c3b2ebcaecab63e03b3f8592bdf34bc5d58c009d6273a61aa0b52627496d",
          "sha1": "40d46e53ec5e58e7d323f42968765ef3cdfad5bf",
          "md5": "c28e49525e9cc22fac40cca5b02d1740"
        }
      ]
    }
  ]
}
