{
  "formatVersion": "1.1",
  "component": {
    "group": "io.carrotquest",
    "module": "cqandroid-lib",
    "version": "1.0.54-commonRelease",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "bxez7fkpefh7nmsd3jt25qqp6e"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.vanniktech",
          "module": "rxpermission",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.35.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.35.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.14"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "cqandroid-lib-1.0.54-commonRelease.aar",
          "url": "cqandroid-lib-1.0.54-commonRelease.aar",
          "size": 294791,
          "sha512": "926756bba2dac352f59540813e5e2b244ef4a909ae031ff1dd01829fd51707d5df2215fec9e8f2dd70e82501c3a7f7ae351d1cf695372474afe6345d1184e1d1",
          "sha256": "0486fac182a9e170fdb3bdc3f34b4ecbef39948246f40cb040d98ff30d5ff40d",
          "sha1": "4bd12122bfbe7e144c406b0643f140aaa83bc535",
          "md5": "a2aaf91973d236c23d136b935f15fb84"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.vanniktech",
          "module": "rxpermission",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "cqandroid-lib-1.0.54-commonRelease.aar",
          "url": "cqandroid-lib-1.0.54-commonRelease.aar",
          "size": 294791,
          "sha512": "926756bba2dac352f59540813e5e2b244ef4a909ae031ff1dd01829fd51707d5df2215fec9e8f2dd70e82501c3a7f7ae351d1cf695372474afe6345d1184e1d1",
          "sha256": "0486fac182a9e170fdb3bdc3f34b4ecbef39948246f40cb040d98ff30d5ff40d",
          "sha1": "4bd12122bfbe7e144c406b0643f140aaa83bc535",
          "md5": "a2aaf91973d236c23d136b935f15fb84"
        }
      ]
    }
  ]
}
